### PR TITLE
divide pytest_clld into submodules, prevent direct imports

### PR DESCRIPTION
**Pull request by xflr6**
- add selenium.get_page()
- fix bare excepts
- refactor DataTable.get_info w/ Info.fromtext()
- unify time.sleep() calls with a common tick

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]
Looks good. Should be backwards compatible, right?

**Comment by xflr6** [comment]
Yes, as long as we did not already `import` something from `pytest_clld` somewhere.
Note that we don't need a `pytest_plugins` line downstream:
https://github.com/clld/sails/blob/abf6e969f61347aeff4db1a9dfaec2ad41840969/sails/tests/test_functional.py#L3
AFAIU, this line actually tries import the `clld` module as pytest plugin (`pytest11` registered plugins load before that line to allow parsing command-line switches).

**Comment by xrotwang** [comment]
I think nothing is explicitly imported, i.e. everything is used via fixtures.

**Comment by xflr6** [comment]
Allright, just checking (initially I had to import `PageObject` in https://github.com/clld/glottolog3/tree/clld4, but now there is `selenium.get_page()` for that here), merging.

**Pull request merged**
